include(GoogleTest)
add_library(xgct_dma_example STATIC ../examples/circular_dma.c)
set_target_properties(xgct_dma_example PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
target_link_libraries(xgct_dma_example PUBLIC xgct::ring_buffer)
xgct_warnings(xgct_dma_example)
add_executable(xgct_tests unit/test_migration.cpp unit/test_containers.cpp unit/test_dma_cycle.cpp)
set_target_properties(xgct_tests PROPERTIES CXX_STANDARD 17 CXX_STANDARD_REQUIRED YES CXX_EXTENSIONS NO)
target_link_libraries(xgct_tests PRIVATE xgct::list xgct::hash xgct::bitset xgct::ring_buffer xgct_dma_example GTest::gtest_main)
xgct_warnings(xgct_tests)
gtest_discover_tests(xgct_tests DISCOVERY_MODE POST_BUILD PROPERTIES LABELS "unit" TIMEOUT 30)
