set(root "${BINARY}/consumers/${CASE}")
file(MAKE_DIRECTORY "${root}/source")
set(options "")
if(DEPENDENCY_PREFIX)
    string(APPEND options "list(APPEND CMAKE_PREFIX_PATH \"${DEPENDENCY_PREFIX}\")\n")
endif()
if(CASE MATCHES "^supplied_(.+)$")
    set(component list)
    string(APPEND options "set(XGCT_BUILD_HASH OFF CACHE BOOL \"\" FORCE)\nset(XGCT_BUILD_BITSET OFF CACHE BOOL \"\" FORCE)\nset(XGCT_BUILD_RING_BUFFER OFF CACHE BOOL \"\" FORCE)\nset(XGCT_BUILD_TESTS OFF CACHE BOOL \"\" FORCE)\n")
    if(CASE STREQUAL "supplied_good")
        string(APPEND options "add_subdirectory(\"${SOURCE}\" first)\nadd_subdirectory(\"${SOURCE}\" second)\n")
    else()
        set(abi 9)
        if(CASE STREQUAL "supplied_incomplete")
            set(abi 1)
            string(APPEND options "set(XGCT_BUILD_BITSET ON CACHE BOOL \"\" FORCE)\n")
        endif()
        string(APPEND options "add_library(xgct::list STATIC IMPORTED)\nset_target_properties(xgct::list PROPERTIES XGCT_VERSION 0.1.0 XGCT_ABI_VERSION ${abi})\nadd_subdirectory(\"${SOURCE}\" module)\n")
        set(expect_failure TRUE)
    endif()
elseif(CASE MATCHES "^source_(.+)$")
    set(component "${CMAKE_MATCH_1}")
    foreach(item list hash bitset ring_buffer)
        string(TOUPPER "${item}" upper)
        string(APPEND options "set(XGCT_BUILD_${upper} OFF CACHE BOOL \"\" FORCE)\n")
    endforeach()
    string(TOUPPER "${component}" upper)
    string(APPEND options "set(XGCT_BUILD_${upper} ON CACHE BOOL \"\" FORCE)\n")
    string(APPEND options "set(XGCT_BUILD_TESTS OFF CACHE BOOL \"\" FORCE)\n")
    string(APPEND options "set(XGCT_STATUS_SOURCE_DIR \"${STATUS_SOURCE}\" CACHE PATH \"\" FORCE)\n")
    string(APPEND options "set(XGS_BUILD_STRINGS OFF CACHE BOOL \"\" FORCE)\n")
    string(APPEND options "add_subdirectory(\"${SOURCE}\" module)\n")
elseif(CASE MATCHES "^installed_(.+)$")
    set(component "${CMAKE_MATCH_1}")
    set(install_binary "${BINARY}")
    if(component STREQUAL "missing")
        execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SOURCE}" -B "${root}/minimal" -G "${GENERATOR}"
            "-DCMAKE_C_COMPILER=${CC}" -DXGCT_BUILD_HASH=OFF -DXGCT_BUILD_BITSET=OFF -DXGCT_BUILD_RING_BUFFER=OFF
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Minimal configure failed: ${output}${error}")
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" --build "${root}/minimal" --config "${CONFIG}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Minimal build failed: ${output}${error}")
        endif()
        set(install_binary "${root}/minimal")
        set(component hash)
        set(expect_failure TRUE)
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" --install "${install_binary}" --prefix "${root}/prefix"
        --config "${CONFIG}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Install failed: ${output}${error}")
    endif()
    string(APPEND options "list(PREPEND CMAKE_PREFIX_PATH \"${root}/prefix\")\n")
    set(version 0.1.0)
    if(component STREQUAL "wrong_version")
        set(component list)
        set(version 9.0.0)
        set(expect_failure TRUE)
    elseif(component STREQUAL "unknown")
        set(expect_failure TRUE)
    elseif(component STREQUAL "bad_abi")
        set(component list)
        string(APPEND options "add_library(xgct::list STATIC IMPORTED)\nset_target_properties(xgct::list PROPERTIES XGCT_VERSION 0.1.0 XGCT_ABI_VERSION 9)\n")
        set(expect_failure TRUE)
    elseif(component STREQUAL "bad_type")
        set(component list)
        string(APPEND options "add_library(xgct::list INTERFACE IMPORTED)\nset_target_properties(xgct::list PROPERTIES XGCT_VERSION 0.1.0 XGCT_ABI_VERSION 1)\n")
        set(expect_failure TRUE)
    elseif(component STREQUAL "optional")
        set(component list)
        string(APPEND options "find_package(xgen_containers 0.1.0 EXACT CONFIG REQUIRED COMPONENTS list OPTIONAL_COMPONENTS absent)\nif(xgen_containers_absent_FOUND)\nmessage(FATAL_ERROR \"Unexpected optional component\")\nendif()\n")
    endif()
    if(component STREQUAL "list")
        string(APPEND options "set(CMAKE_DISABLE_FIND_PACKAGE_xgen_status ON)\n")
    endif()
    string(APPEND options "find_package(xgen_containers ${version} EXACT CONFIG REQUIRED COMPONENTS ${component})\n")
else()
    message(FATAL_ERROR "Unknown consumer ${CASE}")
endif()
if(component STREQUAL "list")
    set(code "xgct_list_t list; xgct_list_init(&list); return !xgct_list_validate(&list);")
    string(APPEND options "if(TARGET xgs::status)\nmessage(FATAL_ERROR \"list unexpectedly depends on status\")\nendif()\n")
elseif(component STREQUAL "hash")
    set(code "xgct_hash_t table; xgct_hash_node_t* buckets[1]; return xgct_hash_init(&table, buckets, 1, 2) != XGS_OK;")
elseif(component STREQUAL "bitset")
    set(code "unsigned char bytes[2]; xgct_bitset_t bits; return xgct_bitset_init(&bits, bytes, 2, 9) != XGS_OK;")
else()
    set(code "unsigned char bytes[2]; xgct_ring_buffer_t ring; return xgct_ring_init(&ring, bytes, 2) != XGS_OK;")
endif()
file(WRITE "${root}/source/main.c" "#include <xgen/containers/${component}.h>\n#include <xgen/containers/version.h>\n#if XGCT_ABI_VERSION != 1\n#error ABI mismatch\n#endif\nint main(void) { ${code} }\n")
file(WRITE "${root}/source/CMakeLists.txt" "cmake_minimum_required(VERSION 3.24)\nproject(consumer LANGUAGES C)\n${options}\nadd_executable(consumer main.c)\ntarget_link_libraries(consumer PRIVATE xgct::${component})\nset_target_properties(consumer PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)\nenable_testing()\nadd_test(NAME consume COMMAND consumer)\n")
set(command "${CMAKE_COMMAND}" -S "${root}/source" -B "${root}/build" -G "${GENERATOR}"
    "-DCMAKE_C_COMPILER=${CC}")
if(PLATFORM)
    list(APPEND command -A "${PLATFORM}")
endif()
if(TOOLSET)
    list(APPEND command -T "${TOOLSET}")
endif()
execute_process(COMMAND ${command} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${root}/configure.log" "${output}${error}")
if(expect_failure)
    if(result EQUAL 0)
        message(FATAL_ERROR "Invalid consumer was accepted")
    endif()
    if(NOT "${output}${error}" MATCHES "incompatible|version|not installed|FOUND to FALSE|Incomplete supplied")
        message(FATAL_ERROR "Failure was unrelated: ${output}${error}")
    endif()
    return()
endif()
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Configure failed: ${output}${error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${root}/build" --config "${CONFIG}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Build failed: ${output}${error}")
endif()
execute_process(COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${root}/build" -C "${CONFIG}"
    --output-on-failure --no-tests=error RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Run failed: ${output}${error}")
endif()
